spring:
  profiles:
   active: cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanjeeb-talukdar/microservices-demo-config-repo.git
 #       native:
 #         search-locations: file:///D:/Projects/MayBank/microservices-complete-example/sample-config
  application:
    name: spring-cloud-config-server    
  
info:
  component: String Cloud Config Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#server:
#  port: 80

#management:
#  port: 8995

eureka:
  name: spring-cloud-config-server
  awsAccessId: AKIAIXPIFMO634VRHDWA
  awsSecretKey: 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
  preferSameZone: true
  shouldUseDns: true
  serviceUrl:
    default: http://172.31.12.87/eureka
  client:
    region: us-east-1
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://172.31.12.87/eureka
      us-east-1a: http://172.31.12.87/eureka
  us-east-1:
      availabilityZones: us-east-1a
  instance:
#    hostname: sansoft-spring-cloud-config-server.us-east-1.elasticbeanstalk.com
#    non-secure-port: 80
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
 #   metadataMap:
 #     instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'