spring:
  profiles:
    active: cloud
  application:
    name: products-api-service
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://ip-172-31-2-81.ec2.internal:8080/

info:
  component: Products API Service
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://ip-172-31-11-75.ec2.internal:8080/eureka

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000000
ribbon:
  ConnectTimeout: 6000000
  ReadTimeout: 6000000
     
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'
    
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----