spring:
  profiles:
    active: cloud
  application:
    name: oauth2-jwt-identity-server
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://172.31.6.132/
#      uri: http://localhost:8888           

info:
  component: Oauth2 JWT Authentication Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#server:
#  port: 9999

security:
  user:
    password: password
     
eureka:
  name: oauth2-jwt-identity-server
  awsAccessId: AKIAIXPIFMO634VRHDWA
  awsSecretKey: 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
  preferSameZone: true
  shouldUseDns: true
  serviceUrl:
    default: http://172.31.12.87/eureka
  client:
    region: us-east-1
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://172.31.12.87/eureka
      us-east-1a: http://172.31.12.87/eureka
  us-east-1:
      availabilityZones: us-east-1a
  instance:
    hostname: ip-172-31-13-248.ec2.internal
    non-secure-port: 80
    ip-address: 172-31-13-248
    prefer-ip-address: true
    virtual-host-name: ec2-52-23-235-69.compute-1.amazonaws.com
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    app-group-name: micro-service
    appname: oauth2-jwt-identity-server
 #   metadataMap:
 #     instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'
