spring:
  profiles:
    active: cloud
  application:
    name: products-composite-service
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://sansoft-spring-cloud-config-server.us-east-1.elasticbeanstalk.com/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
info:
  component: Products Composite Service

eureka:
  client:
    serviceUrl:
      defaultZone: http://sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com/eureka

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000000
ribbon:
  ConnectTimeout: 6000000
  ReadTimeout: 6000000
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'