spring:
  application:
    name: turbine-server
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888           

info:
  component: Turbine Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

server:
  port: 8989

management:
  port: 8990

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      
logging:
  level: 
    com.netflix.discovery: 'TRACE'
    org.springframework.cloud: 'TRACE'
    org.springframework.boot: 'TRACE'
    org.springframework.context: 'TRACE'
    org.springframework.integration: 'TRACE'
 
#################################
# Turbine 
#################################
#turbine:
#   aggregator:
#      clusterConfig: myCluster
#   instanceUrlSuffix:
#      myCluster: /hystrix.stream
#   ConfigPropertyBasedDiscovery:
#      myCluster:
#        instances: localhost:8082,localhost:8083

turbine:
  instanceInsertPort:
     default: false
  combineHostPort: true
  appConfig: transactions-api-service, accounts-api-service
  clusterNameExpression: new String("default")



