spring:
  aop:
    proxy-target-class: true
  application:
    name: zuul-edge-sso-server
  cloud:
    config:
      enabled: true
      uri: http://ec2-54-175-244-196.compute-1.amazonaws.com/
#      uri: http://localhost:8888           

info:
  component: Edge Server Zuul (API Gateway + SSO + Login UI)
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#server:
#  port: 9991

#management:
#  port: 8983

eureka:
  name: zuul-edge-sso-server
  awsAccessId: AKIAIXPIFMO634VRHDWA
  awsSecretKey: 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
  preferSameZone: true
  shouldUseDns: true
  serviceUrl:
    default: http://ec2-52-90-165-34.compute-1.amazonaws.com/eureka
  client:
    region: us-east-1
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://ec2-52-90-165-34.compute-1.amazonaws.com/eureka
      us-east-1a: http://ec2-52-90-165-34.compute-1.amazonaws.com/eureka
  us-east-1:
      availabilityZones: us-east-1a
  instance:
    hostname: ec2-52-204-13-89.compute-1.amazonaws.com
    non-secure-port: 80
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
 #   metadataMap:
 #     instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'
    
zuul:
#  ignoredServices: "*"
  routes:
    transactions-api-service: /account-transactions/**
    accounts-api-service: /account-details/**
    oauth2-jwt-identity-server: /auth/**
    products-api-service: /product-catalogue/**

debug: true

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://ec2-52-23-235-69.compute-1.amazonaws.com/oauth/token
      userAuthorizationUri: http://ec2-52-23-235-69.compute-1.amazonaws.com/oauth/authorize
      clientId: maybank-client
      clientSecret: maybank-client-secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
