spring:
  profiles:
    active: cloud
  aop:
    proxy-target-class: true
  application:
    name: zuul-edge-sso-server
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://sansoft-spring-cloud-config-server.us-east-1.elasticbeanstalk.com/

info:
  component: Edge Server Zuul (API Gateway + SSO + Login UI)
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com/eureka
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'
    
zuul:
  routes:
    transactions-api-service: /account-transactions/**
    accounts-api-service: /account-details/**
    oauth2-jwt-identity-server: /auth/**
    products-api-service: /product-catalogue/**

debug: true

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://sansoft-oauth2-jwt-identity-server.us-east-1.elasticbeanstalk.com/oauth/token
      userAuthorizationUri: http://sansoft-oauth2-jwt-identity-server.us-east-1.elasticbeanstalk.com/oauth/authorize
      clientId: maybank-client
      clientSecret: maybank-client-secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
          

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000000
ribbon:
  ConnectTimeout: 6000000
  ReadTimeout: 6000000