spring:
  profiles:
    active: cloud
  application:
    name: eureka-discovery-server
  cloud:
    config:
      enabled: true
      uri: http://sansoft-spring-cloud-config-server.us-east-1.elasticbeanstalk.com/     

info:
  component: Discovery Server Eureka (Service Registry)
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
   awsAccessId: AKIAIXPIFMO634VRHDWA
   awsSecretKey: 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
   name: eureka-discovery-server
   shouldUseDns: true
   preferSameZone: true
   region:
     us-east-1
   us-east-1:
      availabilityZones: us-east-1b
   serviceUrl:
      us-east-1b: http://sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com/eureka
   instance:   
     hostname: sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com
     non-secure-port: 80
     leaseRenewalIntervalInSeconds: 10
     statusPageUrlPath: /info
     healthCheckUrlPath: /health
   client:
    region: us-east-1
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com/eureka
      us-east-1b: http://sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com/eureka  
   server:
     waitTimeInMsWhenSyncEmpty: 0
 
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: ERROR
    org.springframework.cloud: ERROR
    org.springframework.boot: ERROR
    org.springframework: ERROR