spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: 
        native:
          search-locations: file:///D:/Projects/MayBank/microservices-complete-example/sample-config
  application:
    name: config-server    
  
info:
  component: String Cloud Config Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

server:
  port: 8888

management:
  port: 8995

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      
logging:
  level: 
    com.netflix.discovery: 'TRACE'
    org.springframework.cloud: 'TRACE'
    org.springframework.boot: 'TRACE'
    org.springframework.context: 'TRACE'
    org.springframework.integration: 'TRACE'
 
  
      